services:
  db:
    ports:
      - "3307:3306"
    networks:
      - jenkinsnet
    image: mariadb
    container_name: brain_db
    environment:
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_DATABASE: brAIn
      MYSQL_USER: root
      MYSQL_PASSWORD: ssafy
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: jkw1025/testimage
    container_name: brain_backend
    ports:
      - "8080:8080"
    networks:
      - jenkinsnet
    environment:
      - SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/brAIn?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME: ssafy
      - SPRING_DATASOURCE_PASSWORD: ssafy
      - SPRING_JPA_HIBERNATE_DDL_AUTO: update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MariaDBDialect

    depends_on:
      - db
    volumes:
      - backend-data:/var/lib/backend


networks:
  jenkinsnet:
    name: jenkinsnetd
    driver: bridge

volumes:
  db-data:
  backend-data:
